image: tobitheo/gluon-build-docker:0.5

trigger:
  type: deploy
  script:
    - source version.sh
    - git tag "$RELEASE_VERSION" "$CI_BUILD_REF" # just make sure the version does not exist already
    - echo "Building Gluon ${GLUON_UPSTREAM_TAG} and commit ${CI_BUILD_REF} for FFSAAR version ${RELEASE_VERSION} from the ${CI_BUILD_REF_NAME} branch"
    - curl -X POST -F "token=$CI_SECRET" -F "ref=master" -F "variables[GLUON_UPSTREAM_TAG]=$GLUON_UPSTREAM_TAG" -F "variables[RELEASE_REF]=$CI_BUILD_REF" -F "variables[RELEASE_BRANCH]=$CI_BUILD_REF_NAME" -F "variables[RELEASE_VERSION]=$RELEASE_VERSION" https://git.hacksaar.de/api/v3/projects/30/trigger/builds
  only:
    - experimental
    - beta
    - stable
